import type { Item } from '@/components/templates/ListLinksCollection.vue'

export const categories = [
  '各種図書館が所蔵している資料を探す',
  '雑誌（論文）、図書の情報を探す',
  '出版情報',
  '研究者、研究活動情報',
]

export const items: Item[] = [
  {
    name: 'CiNii Research',
    url: 'https://cir.nii.ac.jp/',
    category: '各種図書館が所蔵している資料を探す',
    overseas: false,
    author: '国立情報学研究所 (NII)',
    text: '国内で発行された雑誌論文や紀要論文、研究データの情報を検索することができる',
  },
  {
    name: 'CiNii Books',
    url: 'https://ci.nii.ac.jp/books/',
    category: '各種図書館が所蔵している資料を探す',
    overseas: false,
    author: '国立情報学研究所 (NII)',
    text: '国内の大学図書館等の蔵書（所蔵している図書、雑誌、その他の資料）を検索できる',
  },
  {
    name: '国立国会図書館サーチ',
    url: 'https://iss.ndl.go.jp/',
    category: '各種図書館が所蔵している資料を探す',
    overseas: false,
    author: '国立国会図書館 (NDL)',
    text: '国立国会図書館をはじめ、全国の公共図書館、公文書館、美術館や学術研究機関等が提供する資料、デジタルコンテンツを統合的に検索できる',
  },
  {
    name: '神奈川県立の図書館 県内横断検索',
    url: 'https://ufinity.pen-kanagawa.ed.jp/?page_id=722',
    category: '各種図書館が所蔵している資料を探す',
    overseas: false,
    author: '神奈川県立図書館',
    text: '神奈川県立図書館と、県内公共図書館の横断検索が可能',
  },
  {
    name: '横浜市立図書館所蔵検索ページ',
    url: 'https://opac.lib.city.yokohama.lg.jp/winj/opac/top.do?lang=ja',
    category: '各種図書館が所蔵している資料を探す',
    overseas: false,
    author: '横浜市立図書館',
    text: '市内地区センター蔵書検索も可能',
  },
  {
    name: 'British Library Catalogue',
    url: 'https://catalogue.bl.uk/nde/home?vid=44BL_MAIN:BLL01_NDE',
    category: '各種図書館が所蔵している資料を探す',
    overseas: true,
    author: 'British Library (BL)',
    text: '英国図書館（BL）のコレクション検索',
  },
  {
    name: 'Library Hub Discover',
    url: 'https://discover.libraryhub.jisc.ac.uk/',
    category: '各種図書館が所蔵している資料を探す',
    overseas: true,
    author: 'Joint Information Systems Committee (JISC)',
    text: 'イギリスの大学図書館の蔵書横断検索。BLDSCで求める資料を利用できない場合（紛失、破損、所蔵なし等）、協力館に依頼してもらえる',
  },
  {
    name: 'Library of congress Catalog',
    url: 'https://catalog.loc.gov',
    category: '各種図書館が所蔵している資料を探す',
    overseas: true,
    author: 'Library of Conygess (LC)',
    text: 'アメリカの議会図書館(LC)、大学、専門図書館の蔵書検索',
  },
  {
    name: 'IRDB',
    url: 'https://irdb.nii.ac.jp/',
    category: '雑誌（論文）、図書の情報を探す',
    overseas: false,
    author: '国立情報学研究所 (NII)',
    text: '日本の学術機関リポジトリに蓄積された学術情報を横断的に検索できる',
  },
  {
    name: '国立国会図書館サーチ',
    url: 'http://opac.ndl.go.jp/',
    category: '雑誌（論文）、図書の情報を探す',
    overseas: false,
    author: '国立国会図書館 (NDL)',
    text: '国立国会図書館をはじめ、全国の公共図書館、公文書館、美術館や学術研究機関等が提供する資料、デジタルコンテンツを統合的に検索できる',
  },
  {
    name: '国文学論文目録データベース',
    url: 'http://base1.nijl.ac.jp/~rombun/',
    category: '雑誌（論文）、図書の情報を探す',
    overseas: false,
    author: '国文学研究資料館',
    text: '国文学研究資料館で所蔵している日本国内で発表された文献に収められた、日本文学・日本語学・日本語教育の研究論文に関する情報を掲載',
  },
  {
    name: 'ERIC',
    url: 'http://eric.ed.gov/',
    category: '雑誌（論文）、図書の情報を探す',
    overseas: true,
    author: 'Education Resources Information Center',
    text: '教育学関係の雑誌論文の書誌情報を中心に収録',
  },
  {
    name: '本の総合カタログ Books（出版書誌データベース）',
    url: 'http://www.books.or.jp/',
    category: '出版情報',
    overseas: false,
    author: '日本出版インフラセンター',
    text: '現在国内で出版されている図書を検索できる。『日本書籍総目録』の最新・Web版。更新が不定期なので、最新情報に関しては各出版社のHPをチェックすると良い',
  },
  {
    name: 'e-hon',
    url: 'http://www.e-hon.ne.jp/bec/EB/Top',
    category: '出版情報',
    overseas: false,
    author: 'トーハン',
    text: '国内で販売されている書籍検索。注文して書店で受け取る事ができる',
  },
  {
    name: 'J-GLOBAL',
    url: 'http://jglobal.jst.go.jp/',
    category: '研究者、研究活動情報',
    overseas: false,
    author: '国立研究開発法人科学技術振興機構(JST)',
    text: '研究者や文献，特許，研究課題などの情報を搭載し、それらを相互に関連付けた科学技術情報の総合サイト',
  },
  {
    name: 'KAKEN',
    url: 'http://kaken.nii.ac.jp/',
    category: '研究者、研究活動情報',
    overseas: false,
    author: '国立情報学研究所（NII）',
    text: '文部科学省および日本学術振興会が交付する科学研究費補助金により行われた研究の当初採択時のデータ（採択課題）と研究成果の概要（研究実績報告，研究成果概要）を収録',
  },
  {
    name: 'researchmap（リサーチマップ）',
    url: 'https://researchmap.jp/',
    category: '研究者、研究活動情報',
    overseas: false,
    author: '国立研究開発法人科学技術振興機構（JST）',
    text: '研究者が業績を管理・発信できるようにすることを目的とした、データベース型研究者総覧',
  },
]
