import type { NewspaperCat } from '@/types/newspaper'

export const updateDate = '2026年7月現在'

export const items: NewspaperCat[] = [
  {
    category: '日本語（全国紙・地方紙）',
    newspapers: [
      {
        title: '朝日新聞',
        subTitle: '',
        country: '',
        publisher: '',
        cycle: '日刊',
        retentionPeriod: '最新3か月分',
        location: '2F新聞',
        note: '<ul><li>朝日新聞クロスサーチ（オンライン）<br />1879（明治12）～継続中</li></ul>',
      },
      {
        title: '朝日新聞',
        subTitle: '朝日新聞：復刻版（明治・大正編）',
        country: '',
        publisher: '',
        cycle: '',
        retentionPeriod: '1888（明治21）7月～1926（大正15 *昭和元年)',
        location: '5F書庫',
        note: '',
      },
      {
        title: '朝日新聞',
        subTitle: '朝日新聞：復刻版（昭和編）',
        country: '',
        publisher: '',
        cycle: '',
        retentionPeriod: '1927（昭和2）～1955（昭和30）',
        location: '5F書庫',
        note: '',
      },
      {
        title: '朝日新聞',
        subTitle: '朝日新聞 縮刷版',
        country: '',
        publisher: '',
        cycle: '',
        retentionPeriod: '1966（昭和41）／1988（昭和63）～継続中',
        location: '1F雑誌・5F書庫',
        note: '当年度以前は5階書庫。 利用の際は2階カウンターに申し込み。',
      },
      {
        title: '朝日新聞',
        subTitle: '朝日新聞 マイクロフィルム',
        country: '',
        publisher: '',
        cycle: '',
        retentionPeriod:
          '1935（昭和10）～1942（昭和17）／1944（昭和19）～1945（昭和20）／1947（昭和22）～1954（昭和29）（欠号あり）',
        location: '1F貴重書庫',
        note: '利用の際は2階カウンターに申し込み。',
      },
      {
        title: '神奈川新聞',
        subTitle: '',
        country: '',
        publisher: '',
        cycle: '日刊',
        retentionPeriod: '最新3か月分',
        location: '2F新聞',
        note: '',
      },
      {
        title: '産経新聞',
        subTitle: '',
        country: '',
        publisher: '',
        cycle: '日刊',
        retentionPeriod: '最新3か月分',
        location: '2F新聞',
        note: '',
      },
      {
        title: '東京新聞',
        subTitle: '',
        country: '',
        publisher: '',
        cycle: '日刊',
        retentionPeriod: '最新3か月分',
        location: '2F新聞',
        note: '',
      },
      {
        title: '東京新聞',
        subTitle: 'みやこ新聞・都新聞（東京新聞の前身）：復刻版',
        country: '',
        publisher: '',
        cycle: '',
        retentionPeriod: '1888（明治21）11月～1937（昭和12）6月　（欠号あり）',
        location: '1F雑誌',
        note: '',
      },
      {
        title: '日本経済新聞',
        subTitle: '',
        country: '',
        publisher: '',
        cycle: '日刊',
        retentionPeriod: '最新3か月分',
        location: '2F新聞',
        note: '<ul><li>日経テレコン21（オンライン）<br />1981(昭和56）～継続中</li></ul>',
      },
      {
        title: '毎日新聞',
        subTitle: '',
        country: '',
        publisher: '',
        cycle: '日刊',
        retentionPeriod: '最新3か月分',
        location: '2F新聞',
        note: '<ul><li>マイサク（オンライン）<br />1872（明治5）～継続中</li></ul>',
      },
      {
        title: '毎日新聞',
        subTitle: '毎日新聞 縮刷版',
        country: '',
        publisher: '',
        cycle: '',
        retentionPeriod: '1967（昭和42)2月～1988(昭和63）1月',
        location: '5F書庫',
        note: '',
      },
      {
        title: '毎日新聞',
        subTitle: '毎日新聞（横濱毎日新聞）：復刻版',
        country: '',
        publisher: '',
        cycle: '',
        retentionPeriod: '1870（明治3）～1906（昭和63）6月',
        location: '1F雑誌',
        note: '',
      },
      {
        title: '読売新聞',
        subTitle: '',
        country: '',
        publisher: '',
        cycle: '日刊',
        retentionPeriod: '最新3か月分',
        location: '2F新聞',
        note: '<ul><li>ヨミダス（オンライン）<br />1874（明治7）～継続中</li></ul>',
      },
    ],
  },
  {
    category: '外国語',
    newspapers: [
      {
        title:
          'Die Zeit : Wochenzeitung für Politik, Wirtschaft, Handel und Kultur',
        subTitle: '',
        country: 'ドイツ',
        publisher: '',
        cycle: '週刊',
        retentionPeriod: '最新3か月分',
        location: '2F新聞',
        note: '',
      },
      {
        title:
          'International New York Times : DISTRIBUTED WITH The Japan Times',
        subTitle: '',
        country: '日本',
        publisher: '',
        cycle: '日刊',
        retentionPeriod: '最新3か月分',
        location: '2F新聞',
        note: '',
      },
      {
        title: 'The Japan Times',
        subTitle: '',
        country: '日本',
        publisher: '',
        cycle: '日刊',
        retentionPeriod: '最新3か月分',
        location: '2F新聞',
        note: '',
      },
      {
        title: '중앙 일보. （中央日報）',
        subTitle: '',
        country: '韓国',
        publisher: '',
        cycle: '日刊',
        retentionPeriod: '最新3か月分',
        location: '2F新聞',
        note: '',
      },
    ],
  },
  {
    category: '専門紙・その他',
    newspapers: [
      {
        title: '教育学術新聞',
        subTitle: '',
        country: '',
        publisher: '教育学術新聞',
        cycle: '週刊',
        retentionPeriod: '最新1年分',
        location: '2F新聞',
        note: '',
      },
      {
        title: 'キリスト教学校教育',
        subTitle: '',
        country: '',
        publisher: 'キリスト教学校教育同盟',
        cycle: '月刊',
        retentionPeriod: '最新1年分',
        location: '2F新聞',
        note: '',
      },
      {
        title: '新聞協会報',
        subTitle: '',
        country: '',
        publisher: '日本新聞協会',
        cycle: '週刊',
        retentionPeriod: '最新1年分',
        location: '2F新聞',
        note: '',
      },
      {
        title: '週刊読書人',
        subTitle: '',
        country: '',
        publisher: '読書人',
        cycle: '週刊',
        retentionPeriod: '最新1年分',
        location: '2F新聞',
        note: '',
      },
      {
        title: '日本教育新聞',
        subTitle: '',
        country: '',
        publisher: '日本教育新聞社',
        cycle: '週刊',
        retentionPeriod: '最新1年分',
        location: '2F新聞',
        note: '',
      },
    ],
  },
]
